name: Hugo build and deploy 

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ['Update theme']
    types:
      - completed
  workflow_dispatch:

jobs:
  Actions-Hugo-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build Hugo static files
        run: hugo --gc --minify --logLevel info

#      - name: Deploy to Github Pages
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          # See https://github.com/JamesIves/github-pages-deploy-action#configuration-
#          branch: gh-pages
#          folder: public
#          clean: true
#          single-commit: true

      - name: rsync deployments
        uses: Burnett01/rsync-deployments@7.0.1
        with:
        #https://github.com/marketplace/actions/rsync-deployments-action
          switches: -avzr --delete
          path: public/
          remote_path: /www/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
