name: Hugo build and deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'sendurl/**'
  workflow_run:
    workflows: ['Update theme']
    types:
      - completed
  workflow_dispatch:

jobs:
  Actions-Hugo-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build Hugo static files
        run: hugo --gc --minify --logLevel info

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          #https://github.com/JamesIves/github-pages-deploy-action#configuration-
          branch: blog
          folder: public
          clean: true
          single-commit: true

      - name: Rsync deployments
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          #https://github.com/marketplace/actions/rsync-deployments-action
          switches: -avzr --delete
          path: public/
          remote_path: /www/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}

      - name: Run shell script
        run: |
          chmod +x ./sendurl/sendurl_baidu.sh
          ./sendurl/sendurl_baidu.sh
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add sendurl/
          git commit -m "sendurl changes"
          git push
        env:
          baidu_apiurl: ${{ secrets.BAIDU_APIURL }}   #脚本引入secrets变量

      - name: indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          # https://github.com/bojieyang/indexnow-action
          sitemap-location: "https://www.5dzone.com/sitemap.xml"
          since: 1
          since-unit: "week"
          key: ${{ secrets.INDEXNOW_KEY }}
          key-location: https://www.5dzone.com/${{ secrets.INDEXNOW_KEY }}.txt