# File: .github/workflows/Update-HugoTheme.yml 

name: Update theme

on:
  schedule:
    - cron: '0 22 * * *'  # 每天执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  Update-HugoTheme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Update theme
      run: |
        if [ ! -e "$SUBFOLDER" ];then
            git subtree add --prefix=$SUBFOLDER $REPO_ADDR $TARGET_BRANCH --squash -m "第一次下载FixIt主题"
        else
            git subtree pull --prefix=$SUBFOLDER $REPO_ADDR $TARGET_BRANCH --squash -m "更新FixIt主题"
        fi
      env:
        SUBFOLDER: themes/FixIt
        REPO_ADDR: https://github.com/hugo-fixit/FixIt
        TARGET_BRANCH: master

    - name: push changes
      run: |
        git push

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 2
